In [2]:
import pandas as pd

print(pd.__version__)

3.0.5

In [3]:
df = pd.read_csv("dirty_school_data.csv")
df

,نام,کد_ملی,تاریخ_تولد_میلادی,پایه_تحصیلی,رشته_تحصیلی,وزن,قد,معدل,شماره_تلفن,شهریه
0,سجاد کریمی,1463031617,2006-08-14,نهم,علوم تجربی,63.9 lb,184,13.47,09842524105,"$15,000,000"
1,NaN,6688937346,12-May-10,دهم,ادبیات و علوم انسانی,87,1.79,NaN,0999 016 2720,25000000
2,ترانه جعفری,4589297500,2011-02-26,هشتم,ادبیات و علوم انسانی,84 kg,167,11.32,09424154152,"25,000,000"
3,زهرا نجفی,2048996423,1279756800,دهم,فنی حرفه‌ای,145.5 lb,194,نامشخص,00989016668700,"$5,000,000"
4,نگار نجفی,5614978403,2012-09-20,7,فنی حرفه‌ای,66,189,13.28,ندارد,"$75,000,000"
...,...,...,...,...,...,...,...,...,...,...
99,رضا احمدی,9632595327,1301270400,یازدهم,تجربی,30 kg,1.65,نامشخص,0939 500 4797,45000000
100,فاطمه صادقی,284395995,18/02/2008,پایه دهم,فنی حرفه‌ای,54 kg,1.55,21.91,NaN,2000000
101,مریم بهرامی,6805891135,2012-11-14,دهم,علوم انسانی,83 kg,146,15.19,00989993756798,NaN
102,سجاد کاظمی,7676772190,2008-06-22,هفتم,کاردانش,56kg,150 cm,17.73,ندارد,0 تومان
103,فاطمه محمدی,4138367024,NaN,یازدهم,علوم انسانی,NaN,1.45,16.37,0961 990 6234,2000000

In [ ]:
#cleaning name

# written by reza & baayram

# تمیز کاری ستون نام

invalid_text_values = ['', 'ندارد', 'NAN', 'nan', 'None', 'نامشخص']
df.shape
df.drop_duplicates(inplace=True)
df.shape
df['وضعیت'] = 'معتبر'

def is_invalid_name(value):
    name_str_value = str(value).strip()
    
    if name_str_value in invalid_text_values:
        return True
        
    return False

invalid_name = df['نام'].apply(is_invalid_name)

df.loc[invalid_name, 'وضعیت'] = 'نامعتبر'
df.loc[invalid_name, 'نام'] = 'مهمان'



# تمیز کاری ستون کد ملی

def is_valid(code):
    code = str(code).strip()
    if not (len(code) == 10 and code.isdigit()):
        return False
    digits = [int(n) for n in code]
    total = sum(digits[i] * (10 - i) for i in range(9))
    remainder = total % 11
    control_digit = digits[9]
    return control_digit == (remainder if remainder < 2 else 11 - remainder)

invalid_code = ~df['کد_ملی'].apply(is_valid)
df.loc[invalid_code, 'وضعیت'] = 'نامعتبر'


#تمیز کاری پایه تحصیلی

grades = [
    "اول","دوم","سوم","چهارم","پنجم","ششم","هفتم","هشتم","نهم","دهم","یازدهم","دوازدهم"
]



def clean_grade(value):
    value = value.replace("پایه", "")
    

    number_to_grade = {"1": "اول","2": "دوم","3": "سوم","4": "چهارم","5": "پنجم","6": "ششم","7": "هفتم","8": "هشتم","9": "نهم",
        "10": "دهم", "11": "یازدهم","12": "دوازدهم"
    }

    if pd.isna(value):
        return 0

    if value in number_to_grade:
        return number_to_grade[value]

    if value in grades:
            return value

    else:
        return 0

df["پایه_تحصیلی"] = df["پایه_تحصیلی"].apply(clean_grade)

#تمیز کاری ستون رشته تحصیلی
maygors = [
    "علوم تجربی", "ادبیات و علوم انسانی", "فنی حرفه‌ای", 
    "ریاضی فیزیک", "ریاضی", "علوم انسانی", "تجربی"
]

def clean_maygor(value):
    if pd.isna(value):
        return "نامشخص"

    val = str(value).strip()

    if val in maygors:
        return val
    
    mapping = {
        "تجربی": "علوم تجربی",
        "ریاضی": "ریاضی فیزیک",
        "انسانی": "ادبیات و علوم انسانی"
    }
    
    return mapping.get(val, "نامشخص")

df["رشته_تحصیلی"] = df["رشته_تحصیلی"].apply(clean_maygor)

#تمیز کاری ستون معدل

def is_invalid_score(value):
    str_val = str(value).strip()
    
    if str_val in invalid_text_values:
        return True
    
    try:
        num_val = float(str_val)
        if num_val > 20 or num_val < 0:
            return True
    except ValueError:
        return True 
        
    return False

invalid_score = df['معدل'].apply(is_invalid_score)

df.loc[invalid_score, 'وضعیت'] = 'نامعتبر'
df.loc[invalid_score, 'معدل'] = '0'

df['معدل'] = df['معدل'].astype(float)

#تمیز کاری ستون شهریه

USD_TO_IRR = 195000
df['شهریه'] = df['شهریه'].astype(str).str.strip()


def clean_salary(value):
    str_value = str(value).strip()

    if str_value in invalid_text_values:
        return 0

    try:
        clean_value = (
            str_value
            .replace(',', '')
            .replace('،', '')
            .strip()
        )

        if '$' in clean_value:
            clean_value = clean_value.replace('$', '').strip()
            dollar_value = float(clean_value)
            return dollar_value * USD_TO_IRR
        
        elif 'تومان' in clean_value:
            clean_value = clean_value.replace('تومان', '').strip()
            toman_value = float(clean_value)
            return toman_value * 10

        else:
            return float(clean_value)

    except (ValueError, TypeError):
        return 0


df['شهریه'] = df['شهریه'].apply(clean_salary)
df['شهریه'] = df['شهریه'].round().astype(int)



#تمیز کاری ستون وزن

lb_to_kg = 0.453592
df['وزن'] = df['وزن'].astype(str).str.strip()

def clean_weight(value):
    str_value = str(value).strip()

    if str_value in invalid_text_values:
        return 0

    try:
        clean_value = (
            str_value
            .replace(',', '')
            .replace('،', '')
            .strip()
        )

        if 'lb' in clean_value:
            clean_value = clean_value.replace('lb', '').strip()
            lb_value = float(clean_value)
            return lb_value * lb_to_kg
        
        elif 'pound' in clean_value:
            clean_value = clean_value.replace('pound', '').strip()
            pound_value = float(clean_value)
            return pound_value * lb_to_kg
        
        elif 'kg' in clean_value:
            clean_value = clean_value.replace('kg', '').strip()
            kg_value = float(clean_value)
            return kg_value

        else:
            return float(clean_value)

    except (ValueError, TypeError):
        return 0


df['وزن'] = df['وزن'].apply(clean_weight)
df['وزن'] = df['وزن'].round().astype(int)

# تمیز کاری ستون قد
def clean_height(value):
    if pd.isna(value):
        return 0
    

    val = str(value).lower().replace("cm", "").replace("m", "").strip()
    
    num = float(val)
        
    
    if num < 3:
            return int(num * 100)
    else:
            return int(num)
        

df['قد'] = df['قد'].apply(clean_height)

# تمیز کاری ستون تاریخ
def clean_date(value):

    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    if value in invalid_text_values:
        return pd.NaT

    if value.isdigit():
        return pd.to_datetime(
            int(value),
            unit='s',
            errors='coerce'
        )

    return pd.to_datetime(
        value,
        dayfirst=True,
        errors='coerce'
    )


df['تاریخ_تولد_میلادی'] = df['تاریخ_تولد_میلادی'].apply(clean_date)

# تمیز کاری شماره تلفن
def clean_num(value):
    str_num = str(value).strip()
    
    if str_num in invalid_text_values:
        return 0

    try:
        clean_value = (
            str_num
            .replace(',', '')
            .replace('،', '')
            .replace(' ', '')
            .replace('-', '')
            .replace('0098', '0')
            .strip()
        )

        if not len(clean_value) == 11:
            clean_value = '0'
            return clean_value

        else:
            return clean_value

    except (ValueError, TypeError):
        return 0

df['شماره_تلفن'] = df['شماره_تلفن'].apply(clean_num)




# اشتباهات

"""
Logical Inconsistency: برگرداندن انواع مختلف خروجی از یک تابع (گاهی رشته، گاهی عدد، گاهی بولین).
The None Trap: فراموش کردن return برای حالت‌هایی که شرط if برقرار نیست (باعث حذف شدن داده‌های سالم می‌شد).
The “Inverted Logic” in loc: انتخاب ردیف‌های صحیح به جای ردیف‌های خطا در هنگام جایگزینی.
Mixing Data Types: انجام عملیات ریاضی روی داده‌های رشته‌ای (String) بدون پاکسازی کامل.
Missing else in apply: وقتی از apply استفاده می‌کنی، تابع تو باید برای هر ردیف، حتماً یک خروجی (حتی اگر همان مقدار اصلی باشد) برگرداند.
تبدیل فرمت شماره تلفن: در موارد مشابه به این
9.89086E+11
"""
# df["نام"] =df["نام"].astype(str).str.strip()
# def NameValidate(value):
#     if value == "NAN" or value == "":
#        clean_value = value.replace("NAN","مهمان").replace("","مهمان")
#        return clean_value
#     return value

# df['نام'] = df['نام'].apply(NameValidate)
# df['نام']

# df.loc[df['نام'] == '', 'نام'] = 'Guest'
# df
# df['نام'].dropna()
# df.shape
# df
# df['کد_ملی'] = df['کد_ملی'].astype(str).str.strip()
# def is_valid_national_code(code):
#     if not (len(code) == 10 and code.isdigit()):
#         return '1111111111'

#     digits = [int(d) for d in code]
#     control_digit = digits[9]
    
#     total = sum(digits[i] * (10 - i) for i in range(9))
#     remainder = total % 11
    
#     if remainder < 2:
#         return control_digit == remainder
#     else:
#         return control_digit == (11 - remainder)

# df['کد_ملی'] = df['کد_ملی'].apply(is_valid_national_code)
df.head(50)

C:\Users\hp\AppData\Local\Temp\ipykernel_13132\1360994460.py:246: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(
C:\Users\hp\AppData\Local\Temp\ipykernel_13132\1360994460.py:246: UserWarning: Parsing dates in %Y.%m.%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(
C:\Users\hp\AppData\Local\Temp\ipykernel_13132\1360994460.py:246: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(

,نام,کد_ملی,تاریخ_تولد_میلادی,پایه_تحصیلی,رشته_تحصیلی,وزن,قد,معدل,شماره_تلفن,شهریه,وضعیت
0,سجاد کریمی,1463031617,2006-08-14,نهم,علوم تجربی,29,184,13.47,09842524105,2925000000000,نامعتبر
1,مهمان,6688937346,2010-05-12,0,ادبیات و علوم انسانی,87,179,0.00,09990162720,25000000,نامعتبر
2,ترانه جعفری,4589297500,2011-02-26,هشتم,ادبیات و علوم انسانی,84,167,11.32,09424154152,25000000,نامعتبر
3,زهرا نجفی,2048996423,2010-07-22,دهم,فنی حرفه‌ای,66,194,0.00,09016668700,975000000000,نامعتبر
4,نگار نجفی,5614978403,2012-09-20,هفتم,فنی حرفه‌ای,66,189,13.28,0,14625000000000,نامعتبر
5,مریم نجفی,3040785932,2008-09-14,هفتم,فنی حرفه‌ای,77,0,12.37,09559059929,5850000000000,نامعتبر
6,مهمان,974395339,2007-07-15,هشتم,نامشخص,33,168,11.31,0,2925000000000,نامعتبر
7,فاطمه صادقی,284395995,2008-02-18,0,فنی حرفه‌ای,54,155,0.00,0,2000000,نامعتبر
8,پریسا رضایی,792524191,2011-09-16,هفتم,ریاضی فیزیک,59,163,19.31,9.89086E+11,11700000000000,نامعتبر
9,رها حسینی,2748467737,2010-04-21,0,ادبیات و علوم انسانی,36,190,17.88,0,30000000,نامعتبر
10,سجاد حسینی,1390053293,2012-03-20,دهم,فنی حرفه‌ای,70,1900,18.58,9.89228E+11,12000000,نامعتبر
11,ماهان نجفی,8501429401,2009-11-16,0,نامشخص,93,176,14.36,9.89884E+11,2925000000000,نامعتبر
12,مهمان,3246095396,NaT,دوازدهم,علوم تجربی,95,0,13.90,09706540515,75000000,نامعتبر
13,ماهان طاهری,2232536729,2010-08-24,0,علوم تجربی,39,187,0.00,9.89578E+11,8775000000000,نامعتبر
14,ماهان بهرامی,4270866882,2008-11-10,دوازدهم,نامشخص,38,194,18.29,0,2340000000000,نامعتبر
15,سبحان نوری,3091307562,2008-04-15,0,نامشخص,88,187,15.19,9.89858E+11,8775000000000,نامعتبر
16,مهمان,978820812,2006-06-10,دهم,ریاضی,43,176,16.19,09699854353,25000000,نامعتبر
17,پارسا احمدی,6184959310,2009-03-31,دهم,علوم تجربی,76,180,13.55,09419283276,75000000,نامعتبر
18,نیلوفر,52204727,2010-02-09,0,نامشخص,32,183,14.44,9.89193E+11,0,نامعتبر
20,شقایق رضایی,7980793597,2006-09-11,هشتم,علوم انسانی,38,151,19.91,9.89889E+11,75000000,نامعتبر
21,علی نجفی,1819600133,NaT,دهم,نامشخص,81,177,0.00,09265423511,975000000000,نامعتبر
22,سجاد طاهری,3407451713,2012-08-05,0,ادبیات و علوم انسانی,45,192,13.51,0,14625000000000,نامعتبر
23,شقایق رستمی,6578091343,2010-11-13,هشتم,تجربی,49,141,0.00,09562386922,5000000,نامعتبر
24,مریم,4516808760,NaT,0,نامشخص,84,153,12.88,0,25000000,نامعتبر
25,دانیال رضایی,163159996,2009-08-29,یازدهم,تجربی,90,1750,16.80,09619431142,75000000,نامعتبر
26,زهرا کریمی,3292127799,2012-01-05,دوازدهم,نامشخص,68,144,17.96,09905814770,3900000000000,نامعتبر
27,فاطمه کاظمی,6417080531,2006-06-14,دهم,فنی حرفه‌ای,30,155,15.64,09374529912,5000000,نامعتبر
28,آرش طاهری,2545738757,2011-01-28,هشتم,نامشخص,33,147,11.09,0,120000000,نامعتبر
29,دانیال رستمی,4874016400,2007-06-20,یازدهم,ادبیات و علوم انسانی,84,167,19.45,09280598262,2925000000000,نامعتبر
30,یاسمن کریمی,47868633,2007-09-28,دهم,علوم تجربی,32,166,0.00,09033119079,120000000,نامعتبر
31,شقایق احمدی,3158692322,2006-12-04,دوازدهم,ریاضی,59,190,10.39,09733754330,25000000,نامعتبر
32,امیر فروزان,1226916697,2012-03-16,هشتم,نامشخص,62,161,14.54,09482814893,200000000,نامعتبر
33,آرمین زارعی,4874016400,2012-06-18,نهم,تجربی,94,157,16.35,9.89718E+11,25000000,نامعتبر
34,ماهان قاسمی,10371293,2009-11-08,0,ادبیات و علوم انسانی,89,164,0.00,09542622189,60000000,نامعتبر
35,یاسمن شریفی,2595269495,NaT,0,نامشخص,66,141,19.80,09940974993,11700000000000,نامعتبر
36,زهرا طاهری,8339187851,2007-05-04,0,فنی حرفه‌ای,47,194,12.05,09971870728,30000000,نامعتبر
37,ترانه رستمی,1329121277,NaT,دوازدهم,فنی حرفه‌ای,85,156,18.08,09490352135,45000000,نامعتبر
38,سبحان رستمی,5277221704,2008-03-28,دوازدهم,نامشخص,93,192,17.53,09345054156,3000000,نامعتبر
39,بهار احمدی,6174451,2008-01-04,یازدهم,نامشخص,59,0,0.00,9.89383E+11,14625000000000,نامعتبر
40,پریسا بهرامی,1031051834,NaT,نهم,نامشخص,88,170,10.97,9.89657E+11,5000000,نامعتبر
41,کیان,6449251925,2010-05-25,هشتم,نامشخص,76,161,18.29,09816850542,2000000,نامعتبر
42,شقایق احمدی,15969664,2009-08-23,0,علوم انسانی,39,146,15.24,0,45000000,نامعتبر
43,رویا کاظمی,3396360576,2007-09-16,هفتم,ادبیات و علوم انسانی,92,161,0.00,0,60000000,نامعتبر
44,سبحان نجفی,3484344375,2012-04-14,یازدهم,علوم تجربی,76,165,0.00,09240415747,2340000000000,نامعتبر
45,امیر,3158692322,2007-02-06,0,علوم تجربی,29,170,19.65,09471167190,1657500000000,نامعتبر
46,آرمین قاسمی,3747407482,NaT,یازدهم,نامشخص,82,169,13.85,09713695944,14625000000000,نامعتبر
47,امیرحسین بهرامی,284395995,2007-10-08,0,فنی حرفه‌ای,80,143,17.35,09268705685,25000000,نامعتبر
48,رویا نجفی,9330833016,2011-04-19,نهم,ریاضی فیزیک,48,170,19.64,09540193802,850000,نامعتبر
49,سارا رستمی,799118384,2009-11-30,دهم,علوم انسانی,64,193,19.84,0,8500000,نامعتبر
50,حسین امینی,6774186256,2010-12-31,یازدهم,تجربی,87,193,17.52,09115869380,8775000000000,نامعتبر